import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getSortedBlogsData } from '@lib/notion/blogs'
import Link from 'next/link'
import { GetStaticProps } from 'next'
import { BlogData } from '@localTypes/blog'
import BlogItem from '../components/Items/BlogItem'

interface Props {
  latestBlogData: BlogData[]
}

export const getStaticProps: GetStaticProps = async () => {
  const latestBlogData = await getSortedBlogsData(2);
  return {
    props: {
      latestBlogData,
    },
    revalidate: 60,
  };
};

export default function Home({ latestBlogData }: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div id="recentBlogs" className="flex flex-col mb-24">
          <h1 className="text-2xl md:text-4xl font-extrabold mb-5">
            Latest blogs
          </h1>

          <div className="grid place-items-center">
            <ul className="w-full grid sm:grid-cols-2 gap-x-8 gap-y-24 p-5 list-none">
              {latestBlogData.map((post) => (
                <li className="" key={post.slug}>
                  <BlogItem slug={post.slug} post={post} />
                </li>
              ))}
            </ul>
          </div>
          <Link href="/blog" className="text-xl hover:underline">Read more →</Link>
        </div>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
